spring:
  kafka:
    listeners:
      concurrency: 2
    properties:
      spring.json.trusted.packages: "*"
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    consumer:
      enable-auto-commit: true
      group-id: betvictorconsumer
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: hu.vizicsaba.betvictortask.textstorageservice.service.model.kafka.TextProcessResult
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
configuration:
  datasource:
    host: text-storage-service-postgresql
    port: 5432
    database: textstorage
    username: postgres
    password: admin
  kafka:
    topic: words.processed
